name: clasp_push

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - 'dialog.html'
      - '.claspignore'
      - 'appsscript.json'
      - 'package.json'
      - 'package-lock.json'
      - '!.eslintrc.js'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node install
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install clasp
        run: npm install -g @google/clasp
      - name: create clasp.json
        run: echo '${{ secrets.CLASP_JSON }}' >  .clasp.json
      - name: create clasprc.json
        run: echo '${{ secrets.CLASPRC_JSON }}' >  ~/.clasprc.json
      - name: deploy
        run: clasp push
